### ISSUE TITLE
StandardSPIFlsah crash on SAMD

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt-maker#162]
When initializing the storage system, the StandardSPIFlash crashes in the SPI stack:
```
Breakpoint 1, _pxt_panic::target_panic (statusCode=statusCode@entry=909) at /src/pxtapp/screen---st7735/panic.cpp:256
256     /src/pxtapp/screen---st7735/panic.cpp: No such file or directory.
(gdb) bt
#0  _pxt_panic::target_panic (statusCode=statusCode@entry=909) at /src/pxtapp/screen---st7735/panic.cpp:256
#1  0x000190bc in codal::ZSPI::startTransfer (this=0x20001468, txBuffer=0x0, txSize=0, rxBuffer=0x20007efc "", rxSize=20, doneHandler=0x0, arg=0x0)
    at /src/libraries/codal-samd/src/ZSPI.cpp:324
#2  0x00018c86 in codal::ZSPI::transfer (this=0x20001468, txBuffer=0x0, txSize=0, rxBuffer=0x20007efc "", rxSize=20)
    at /src/libraries/codal-samd/src/ZSPI.cpp:302
#3  0x00013f78 in codal::StandardSPIFlash::sendCommand (this=this@entry=0x200014b4, command=command@entry=3 '\003', addr=addr@entry=0,
    resp=resp@entry=0x20007efc, respSize=respSize@entry=20) at /src/libraries/codal-core/source/drivers/StandardSPIFlash.cpp:55
#4  0x00013fd2 in codal::StandardSPIFlash::readBytes (this=0x200014b4, addr=0, buffer=0x20007efc, len=20)
    at /src/libraries/codal-core/source/drivers/StandardSPIFlash.cpp:91
#5  0x0000b4a2 in codal::snorfs::FS::readHeaders (this=this@entry=0x200014c8) at /src/pxtapp/storage/SNORFS.cpp:344
#6  0x0000b7b0 in codal::snorfs::FS::mount (this=this@entry=0x200014c8) at /src/pxtapp/storage/SNORFS.cpp:445
#7  0x0000ba36 in mount (this=0x200014c8) at /src/pxtapp/storage/SNORFS.cpp:600
#8  codal::snorfs::FS::lock (this=this@entry=0x200014c8) at /src/pxtapp/storage/SNORFS.cpp:599
#9  0x0000ba98 in codal::snorfs::FS::tryMount (this=this@entry=0x200014c8) at /src/pxtapp/storage/SNORFS.cpp:430
#10 0x0000cdc0 in WStorage (this=0x20001468) at /src/pxtapp/storage/storage.cpp:29
#11 storage::getWStorage () at /src/pxtapp/storage/storage.cpp:32
#12 0x0000cde2 in storage::init () at /src/pxtapp/storage/storage.cpp:53
#13 0x00028f68 in ?? ()
#14 0x00028f68 in ?? ()
```

It crashes at
https://github.com/lancaster-university/codal-samd/blame/f0a8ea10c107df7982ffae00721a702472649053/src/ZSPI.cpp#L324

which is called from
https://github.com/lancaster-university/codal-core/blame/b7b314e44543487c7c124da1c966ed690ab6aa7d/source/drivers/StandardSPIFlash.cpp#L55

- [x] Looks like the assert needs to be updated
- [x] afterwards, fibers are not running anymore

**Comment by pelikhan** [comment]
Fixed.
